### ISSUE TITLE
SO3 & SE3

### ISSUE THREAD

**Issue by Mona77** [arraiy/torchgeometry#5]
@edgarriba, Have you seen the GVNN library. It is vision geometry Pytorch library that is written in Lua. @chaneyw was suggesting to add SO3, SE3 transformations as well. Pl let me know what do you think.

**Comment by edgarriba** [comment]
@Mona77 @chaneyw @ethanrublee  gonna open roadmap for v0.2.0 where we should target gvnn and advanced 3d stuff. Are you still up for this ?

**Comment by edgarriba** [comment]
see https://github.com/arraiy/torchgeometry/issues/28
